name: OpenWrt固件编译
on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      VERSION: 19.07.2
      URL: https://github.com/openwrt/openwrt/archive/v19.07.2.tar.gz
    steps:
    - name: 下载
      run: |
        mkdir ok
        cd ok
        wget $URL
        echo "ddddddddddddddd">22.txt
    - name: Create Release
      id: create_release
      uses: monkeyWie/create-release@master
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ env.VERSION }}
       release_name: Release ${{ env.VERSION }}
       draft: false
       prerelease: false
    - name: Upload Release normal windows
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       files: ok/**
