name: OpenWrt固件编译
on:
  watch:
    types: started

jobs:
  build:
    name: demo
    runs-on: ubuntu-18.04
    env:
      VERSION: 19.07.2
      URL: https://github.com/openwrt/openwrt/archive/v19.07.2.tar.gz
    steps:
    - name: 下载和创建
      run: |
        mkdir ok
        cd ok
        wget $URL
        echo "ddddddddddddddd">22.txt
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ env.VERSION }}
       release_name: Release ${{ env.VERSION }}
       body: |
        修改了什么？
       draft: false
       prerelease: false
    - name: Upload Release
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
       asset_path: ok/**
